name: tag-serverless-version
on: 
  push:
    branches:
      - main
      - 1x
jobs:
  tag-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Get Serverless Version
        run: |
          export SERVERLESS_VERSION=$(cat package.json | grep serverless\" | head -1 | awk -F: '{ print $2 }' | sed 's/[",^]//g' | tr -d '[[:space:]]')
          echo "SERVERLESS_VERSION=$SERVERLESS_VERSION" >> $GITHUB_ENV
      - name: GitHub Script
        uses: actions/github-script@v3.1.0
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ env.SERVERLESS_VERSION }}",
              sha: context.sha
            })

